---
- name: Proto Typ - Kreativbrauerei Kehrwieder
  img_src: images/1.jpg
  likes: 0
  dislikes: 0
- name: Pale Ale - Maisel & Friends
  img_src: images/2.jpg
  likes: 0
  dislikes: 0
- name: Pale Ale - Brau Kunst Keller
  img_src: images/3.jpg
  likes: 0
  dislikes: 0
- name: Smoked Porter - Heiden Peters
  img_src: images/4.jpg
  likes: 0
  dislikes: 0
- name: Weisse - Braumanufaktur Potsdam
  img_src: images/5.jpg
  likes: 0
  dislikes: 0
- name: Atlantik Ale - Störtebeker
  img_src: images/6.jpg
  likes: 0
  dislikes: 0
- name: Spark Chili Spiced IPA - Brewcifer
  img_src: images/7.jpg
  likes: 0
  dislikes: 0
- name: Aufwind - Propeller
  img_src: images/8.jpg
  likes: 0
  dislikes: 0
- name: Red Oat Ale - Hopfenstopfer
  img_src: images/9.jpg
  likes: 0
  dislikes: 0
- name: Tripel Karmeliet
  img_src: images/10.jpg
  likes: 0
  dislikes: 0
- name: Rotbier - Bierfabrik Berlin
  img_src: images/11.jpg
  likes: 0
  dislikes: 0
- name: Rummelsnuffs Kraftbock - Bierfabrik Berlin
  img_src: images/12.jpg
  likes: 0
  dislikes: 0
