- {name: Bier 1, img_src: beer1.jpg, likes: 0, dislikes: 0}
- {name: Bier 2, img_src: beer1.jpg, likes: 0, dislikes: 0}
- {name: Bier 3, img_src: beer1.jpg, likes: 0, dislikes: 0}
- {name: Bier 4, img_src: beer1.jpg, likes: 0, dislikes: 0}
- {name: Bier 5, img_src: beer1.jpg, likes: 0, dislikes: 0}
- {name: Bier 6, img_src: beer1.jpg, likes: 0, dislikes: 0}
- {name: Bier 7, img_src: beer1.jpg, likes: 0, dislikes: 0}
- {name: Bier 8, img_src: beer1.jpg, likes: 0, dislikes: 0}
- {name: Bier 9, img_src: beer1.jpg, likes: 0, dislikes: 0}
- {name: Bier 10, img_src: beer1.jpg, likes: 0, dislikes: 0}
- {name: Bier 11, img_src: beer1.jpg, likes: 0, dislikes: 0}
- {name: Bier 12, img_src: beer1.jpg, likes: 0, dislikes: 0}
